server:
  port: 8000
spring:
  application:
    name: cambio-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/microservices_do_0_com_spring_cloud_spring_boot_e_docker
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: cambio_service
  flyway:
    url: jdbc:postgresql://localhost:5432/microservices_do_0_com_spring_cloud_spring_boot_e_docker
    schemas: cambio_service
    user: postgres
    password: admin
  sleuth:
    sampler:
      probability: 1.0
springdoc:
  show-actuator: true
  api-docs:
    path: cambio-service/v3/api-docs
